version: '3.8'
networks:
  app-tier:
    driver: bridge
services:
  db:
    image: mysql:5.7
    container_name: homada_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: homada
      MYSQL_PASSWORD: homada
      MYSQL_DATABASE: Homada_DB
      MYSQL_USER: generic_operator
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0 --explicit_defaults_for_timestamp
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - app-tier
  adminer:
    image: adminer
    container_name: homada_adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-tier
  api:
    container_name: homada_api
    stdin_open: true
    tty: true
    restart: always
    build: .
    ports:
      - 5555:5000
    volumes:
      - ./App:/homada_bot/App
    networks:
      - app-tier
